//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlopsAutoKicker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlopsAutoKicker.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1Congratulations {0} you&apos;ve just been banned..
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow the server rules..
        /// </summary>
        internal static string FollowRules {
            get {
                return ResourceManager.GetString("FollowRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^2Invite your friends; add us to your favorites.
        /// </summary>
        internal static string FriendInviteMessage {
            get {
                return ResourceManager.GetString("FriendInviteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1Stun, Frag, Claymores, Flash, C4, semtex, etc are not allowed..
        /// </summary>
        internal static string GrenadesRules {
            get {
                return ResourceManager.GetString("GrenadesRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use any type of grenades..
        /// </summary>
        internal static string GrenadeUsage {
            get {
                return ResourceManager.GetString("GrenadeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1Congratulations {0} you&apos;ve just been kicked..
        /// </summary>
        internal static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1No deadly killstreaks are allowed. If you wish to use them for XP, call them off map..
        /// </summary>
        internal static string KillstreaksRules {
            get {
                return ResourceManager.GetString("KillstreaksRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use any deadly killstreaks..
        /// </summary>
        internal static string KillStreaksUsage {
            get {
                return ResourceManager.GetString("KillStreaksUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not knife again. .
        /// </summary>
        internal static string KnifeUsage {
            get {
                return ResourceManager.GetString("KnifeUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1Melee knifing is *NOT* allowed. Ballistic Knife is allowed for shooting only..
        /// </summary>
        internal static string KnifingRules {
            get {
                return ResourceManager.GetString("KnifingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1Second Chance is *NOT* allowed..
        /// </summary>
        internal static string PerkRules {
            get {
                return ResourceManager.GetString("PerkRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^0Welcome {0}. Type {1} for server rules..
        /// </summary>
        internal static string PersonalGreet {
            get {
                return ResourceManager.GetString("PersonalGreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^2Type {0} for server rules..
        /// </summary>
        internal static string RulesTrigger {
            get {
                return ResourceManager.GetString("RulesTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^2This server is protected by BlopsAutoKicker created by Balls.
        /// </summary>
        internal static string ServerProtection {
            get {
                return ResourceManager.GetString("ServerProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1This is your only warning. {0} You will be kicked. Type {1} for server rules..
        /// </summary>
        internal static string WarningMessage {
            get {
                return ResourceManager.GetString("WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^1Only sniper rifles, tomahawks, crossbows, and ballistic knifes..
        /// </summary>
        internal static string WeaponRules {
            get {
                return ResourceManager.GetString("WeaponRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use any other weapon than a sniper rifle..
        /// </summary>
        internal static string WeaponUsage {
            get {
                return ResourceManager.GetString("WeaponUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^2Welcome to XtremeDuty Snipers Only. Enjoy your stay!.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
